Repository willGyu/SpringGitTest7, pull requests merged in 2024-11, with the labels that each got.

#10 4 팀원 아이티윌
  SpringGitTest/target/m2e-wtp/web-resources/META-INF/maven/com.itwillbs/web/.gitignore
  SpringGitTest/target/m2e-wtp/web-resources/META-INF/maven/com.itwillbs/web/pom.properties
  SpringGitTest/팀원-아이티윌작업.txt
Labels: good first issue

#25 memberDelete 2
  SpringGitTest/memberDelete 작업.txt
Labels: good first issue

#26 19 작업 끝
  SpringGitTest/19작업.txt
Labels: enhancement

#29 17 feat memberjoin
  SpringGitTest/17작업.txt
Labels: documentation

#28 작업 테스트 커밋.
  SpringGitTest/김상현 memberJoin
Labels: bug
